### ISSUE TITLE
Load failed

### ISSUE THREAD

**Issue by 8thHalfHour** [wburton95/Notepadpp-Gruvbox-Port#1]
I'm getting an error when attempting to apply these themes:

`Load "C:\Program Files\Notepad++\themes\Gruvbox Dark Hard.xml" failed!`

. . . and then NPP crashes.

It's the same for all of the variants.

**Comment by wburton95** [comment]
Hello! My apologies for not responding earlier. I "took a break" from my hobbies during the difficult parts of the pandemic and I am just now starting to get back into things again.

For future reference I believe the issue may reside with notepad++. I experienced a similar issue myself. Try placing your themes under " .../appdata/notepad++/themes". Notepad++ seems to want themes under AppData. If placed under the notepad++ theme directory in ".../Program Files/notepad++/themes" the theme will show as selectable but selecting that theme will crash notepad++.

**Comment by 8thHalfHour** [comment]
I'm sorry I never responded to this. That worked; thanks!
