### ISSUE TITLE
Add a screenshot of the theme in readme.md

### ISSUE THREAD

**Issue by irigone** [wburton95/Notepadpp-Gruvbox-Port#2]
What the title says. People would want to know how it looks (in Notepad++ ofc, not in other editors) before actually using it.

**Comment by wburton95** [comment]
My apologies for not fixing this issue sooner. I don't plan on abandoning this project. I am a big fan of Notepad++ and the Gruvbox themes. I wish to continue work on my port of the theme so I have uploaded a new screenshot of the current work.
